from typing import Literal

from pydantic import BaseModel, Field, model_validator


class MorningBrief(BaseModel):
    """Structured output from Agent 3a — Morning Brief Generator."""

    topic: str = Field(..., description="Today's learning topic")
    key_concepts: list[str] = Field(
        ...,
        min_length=5,
        max_length=5,
        description="Exactly 5 key concepts, each under 20 words",
    )
    misconceptions: list[str] = Field(
        ...,
        min_length=2,
        max_length=2,
        description="Exactly 2 common misconceptions students have about this topic",
    )
    mnemonic: str = Field(
        ..., description="One memorable mnemonic or memory trick for the topic"
    )
    think_about: list[str] = Field(
        ...,
        min_length=3,
        max_length=3,
        description="Exactly 3 thought-provoking questions for the student to ponder",
    )

    @model_validator(mode="after")
    def concepts_under_20_words(self) -> "MorningBrief":
        for concept in self.key_concepts:
            word_count = len(concept.split())
            if word_count > 20:
                raise ValueError(
                    f"key_concept exceeds 20 words ({word_count} words): '{concept}'"
                )
        return self


# ── Agent 3b — Quiz Conductor schemas ─────────────────────────────────────────


class QuizOption(BaseModel):
    """One answer choice in a multiple-choice question."""

    index: int = Field(..., ge=0, le=3, description="0-indexed option position (0–3)")
    text: str = Field(..., description="The answer text shown to the student")


class QuizQuestion(BaseModel):
    """A single MCQ generated by Agent 3b."""

    question_id: str = Field(..., description="Unique slug, e.g. 'q1', 'q2' … 'q5'")
    question: str = Field(..., description="The question text")
    options: list[QuizOption] = Field(
        ..., min_length=4, max_length=4, description="Exactly 4 answer options"
    )
    correct_index: int = Field(
        ..., ge=0, le=3, description="Index of the correct option (0-indexed)"
    )

    @model_validator(mode="after")
    def correct_index_in_options(self) -> "QuizQuestion":
        indices = [o.index for o in self.options]
        if self.correct_index not in indices:
            raise ValueError(
                f"correct_index {self.correct_index} not in option indices {indices}"
            )
        return self


class QuizList(BaseModel):
    """Structured-output wrapper for a 5-question quiz (mirrors MilestoneList pattern)."""

    questions: list[QuizQuestion] = Field(
        ..., min_length=5, max_length=5, description="Exactly 5 MCQs"
    )


class QuizResult(BaseModel):
    """Evaluation output from Agent 3b evaluator."""

    per_question: list[dict] = Field(
        ..., description="[{question_id, correct, feedback}] for each question"
    )
    overall_score: float = Field(
        ..., ge=0.0, le=100.0, description="Arithmetic score: 0.0 – 100.0"
    )
    summary_feedback: str = Field(
        ..., description="2-3 sentence summary feedback for the student"
    )
    recommendation: Literal["advance", "review"] = Field(
        ..., description="'advance' if score >= 70, else 'review'"
    )
